namespace Glacier.StatsViz.Compute;

internal static class GpuStatsKernels
{
    public const string PtxSource = @"//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-37862127
// Cuda compilation tools, release 13.3, V13.3.33
// Based on NVVM 7.0.1
//

.version 9.3
.target sm_89
.address_size 64

	// .globl	statsviz_kde_evaluate_fp32

.visible .entry statsviz_kde_evaluate_fp32(
	.param .u64 statsviz_kde_evaluate_fp32_param_0,
	.param .u64 statsviz_kde_evaluate_fp32_param_1,
	.param .u64 statsviz_kde_evaluate_fp32_param_2,
	.param .u32 statsviz_kde_evaluate_fp32_param_3,
	.param .u32 statsviz_kde_evaluate_fp32_param_4,
	.param .f32 statsviz_kde_evaluate_fp32_param_5,
	.param .f32 statsviz_kde_evaluate_fp32_param_6
)
{
	.reg .pred 	%p<12>;
	.reg .f32 	%f<225>;
	.reg .b32 	%r<49>;
	.reg .b64 	%rd<31>;


	ld.param.u64 	%rd16, [statsviz_kde_evaluate_fp32_param_0];
	ld.param.u64 	%rd14, [statsviz_kde_evaluate_fp32_param_1];
	ld.param.u64 	%rd15, [statsviz_kde_evaluate_fp32_param_2];
	ld.param.u32 	%r24, [statsviz_kde_evaluate_fp32_param_3];
	ld.param.u32 	%r25, [statsviz_kde_evaluate_fp32_param_4];
	ld.param.f32 	%f16, [statsviz_kde_evaluate_fp32_param_5];
	ld.param.f32 	%f17, [statsviz_kde_evaluate_fp32_param_6];
	cvta.to.global.u64 	%rd1, %rd16;
	mov.u32 	%r26, %ntid.x;
	mov.u32 	%r27, %ctaid.x;
	mov.u32 	%r28, %tid.x;
	mad.lo.s32 	%r1, %r27, %r26, %r28;
	setp.ge.s32 	%p1, %r1, %r25;
	@%p1 bra 	$L__BB0_16;

	cvta.to.global.u64 	%rd17, %rd14;
	cvt.s64.s32 	%rd2, %r1;
	mul.wide.s32 	%rd18, %r1, 4;
	add.s64 	%rd19, %rd17, %rd18;
	ld.global.nc.f32 	%f1, [%rd19];
	setp.lt.s32 	%p2, %r24, 4;
	mov.u32 	%r44, 0;
	mov.f32 	%f224, 0f00000000;
	@%p2 bra 	$L__BB0_8;

	add.s32 	%r32, %r24, -4;
	shr.u32 	%r2, %r32, 2;
	add.s32 	%r33, %r2, 1;
	and.b32  	%r43, %r33, 3;
	setp.lt.u32 	%p3, %r32, 12;
	mov.f32 	%f224, 0f00000000;
	mov.u32 	%r44, 0;
	@%p3 bra 	$L__BB0_5;

	sub.s32 	%r38, %r2, %r43;
	mov.f32 	%f224, 0f00000000;
	mov.u32 	%r44, 0;
	mov.u64 	%rd27, %rd1;

$L__BB0_4:
	ld.global.nc.v4.f32 	{%f22, %f23, %f24, %f25}, [%rd27];
	sub.f32 	%f30, %f1, %f22;
	sub.f32 	%f31, %f1, %f23;
	sub.f32 	%f32, %f1, %f24;
	sub.f32 	%f33, %f1, %f25;
	mul.f32 	%f34, %f30, %f30;
	mul.f32 	%f35, %f34, %f16;
	mul.f32 	%f36, %f35, 0fBFB8AA3B;
	ex2.approx.f32 	%f37, %f36;
	add.f32 	%f38, %f224, %f37;
	mul.f32 	%f39, %f31, %f31;
	mul.f32 	%f40, %f39, %f16;
	mul.f32 	%f41, %f40, 0fBFB8AA3B;
	ex2.approx.f32 	%f42, %f41;
	add.f32 	%f43, %f38, %f42;
	mul.f32 	%f44, %f32, %f32;
	mul.f32 	%f45, %f44, %f16;
	mul.f32 	%f46, %f45, 0fBFB8AA3B;
	ex2.approx.f32 	%f47, %f46;
	add.f32 	%f48, %f43, %f47;
	mul.f32 	%f49, %f33, %f33;
	mul.f32 	%f50, %f49, %f16;
	mul.f32 	%f51, %f50, 0fBFB8AA3B;
	ex2.approx.f32 	%f52, %f51;
	add.f32 	%f53, %f48, %f52;
	ld.global.nc.v4.f32 	{%f54, %f55, %f56, %f57}, [%rd27+16];
	sub.f32 	%f62, %f1, %f54;
	sub.f32 	%f63, %f1, %f55;
	sub.f32 	%f64, %f1, %f56;
	sub.f32 	%f65, %f1, %f57;
	mul.f32 	%f66, %f62, %f62;
	mul.f32 	%f67, %f66, %f16;
	mul.f32 	%f68, %f67, 0fBFB8AA3B;
	ex2.approx.f32 	%f69, %f68;
	add.f32 	%f70, %f53, %f69;
	mul.f32 	%f71, %f63, %f63;
	mul.f32 	%f72, %f71, %f16;
	mul.f32 	%f73, %f72, 0fBFB8AA3B;
	ex2.approx.f32 	%f74, %f73;
	add.f32 	%f75, %f70, %f74;
	mul.f32 	%f76, %f64, %f64;
	mul.f32 	%f77, %f76, %f16;
	mul.f32 	%f78, %f77, 0fBFB8AA3B;
	ex2.approx.f32 	%f79, %f78;
	add.f32 	%f80, %f75, %f79;
	mul.f32 	%f81, %f65, %f65;
	mul.f32 	%f82, %f81, %f16;
	mul.f32 	%f83, %f82, 0fBFB8AA3B;
	ex2.approx.f32 	%f84, %f83;
	add.f32 	%f85, %f80, %f84;
	ld.global.nc.v4.f32 	{%f86, %f87, %f88, %f89}, [%rd27+32];
	sub.f32 	%f94, %f1, %f86;
	sub.f32 	%f95, %f1, %f87;
	sub.f32 	%f96, %f1, %f88;
	sub.f32 	%f97, %f1, %f89;
	mul.f32 	%f98, %f94, %f94;
	mul.f32 	%f99, %f98, %f16;
	mul.f32 	%f100, %f99, 0fBFB8AA3B;
	ex2.approx.f32 	%f101, %f100;
	add.f32 	%f102, %f85, %f101;
	mul.f32 	%f103, %f95, %f95;
	mul.f32 	%f104, %f103, %f16;
	mul.f32 	%f105, %f104, 0fBFB8AA3B;
	ex2.approx.f32 	%f106, %f105;
	add.f32 	%f107, %f102, %f106;
	mul.f32 	%f108, %f96, %f96;
	mul.f32 	%f109, %f108, %f16;
	mul.f32 	%f110, %f109, 0fBFB8AA3B;
	ex2.approx.f32 	%f111, %f110;
	add.f32 	%f112, %f107, %f111;
	mul.f32 	%f113, %f97, %f97;
	mul.f32 	%f114, %f113, %f16;
	mul.f32 	%f115, %f114, 0fBFB8AA3B;
	ex2.approx.f32 	%f116, %f115;
	add.f32 	%f117, %f112, %f116;
	ld.global.nc.v4.f32 	{%f118, %f119, %f120, %f121}, [%rd27+48];
	sub.f32 	%f126, %f1, %f118;
	sub.f32 	%f127, %f1, %f119;
	sub.f32 	%f128, %f1, %f120;
	sub.f32 	%f129, %f1, %f121;
	mul.f32 	%f130, %f126, %f126;
	mul.f32 	%f131, %f130, %f16;
	mul.f32 	%f132, %f131, 0fBFB8AA3B;
	ex2.approx.f32 	%f133, %f132;
	add.f32 	%f134, %f117, %f133;
	mul.f32 	%f135, %f127, %f127;
	mul.f32 	%f136, %f135, %f16;
	mul.f32 	%f137, %f136, 0fBFB8AA3B;
	ex2.approx.f32 	%f138, %f137;
	add.f32 	%f139, %f134, %f138;
	mul.f32 	%f140, %f128, %f128;
	mul.f32 	%f141, %f140, %f16;
	mul.f32 	%f142, %f141, 0fBFB8AA3B;
	ex2.approx.f32 	%f143, %f142;
	add.f32 	%f144, %f139, %f143;
	mul.f32 	%f145, %f129, %f129;
	mul.f32 	%f146, %f145, %f16;
	mul.f32 	%f147, %f146, 0fBFB8AA3B;
	ex2.approx.f32 	%f148, %f147;
	add.f32 	%f224, %f144, %f148;
	add.s32 	%r44, %r44, 16;
	add.s64 	%rd27, %rd27, 64;
	add.s32 	%r38, %r38, -4;
	setp.ne.s32 	%p4, %r38, -1;
	@%p4 bra 	$L__BB0_4;

$L__BB0_5:
	setp.eq.s32 	%p5, %r43, 0;
	@%p5 bra 	$L__BB0_8;

	mul.wide.s32 	%rd20, %r44, 4;
	add.s64 	%rd28, %rd1, %rd20;

$L__BB0_7:
	.pragma ""nounroll"";
	ld.global.nc.v4.f32 	{%f149, %f150, %f151, %f152}, [%rd28];
	sub.f32 	%f157, %f1, %f149;
	sub.f32 	%f158, %f1, %f150;
	sub.f32 	%f159, %f1, %f151;
	sub.f32 	%f160, %f1, %f152;
	mul.f32 	%f161, %f157, %f157;
	mul.f32 	%f162, %f161, %f16;
	mul.f32 	%f163, %f162, 0fBFB8AA3B;
	ex2.approx.f32 	%f164, %f163;
	add.f32 	%f165, %f224, %f164;
	mul.f32 	%f166, %f158, %f158;
	mul.f32 	%f167, %f166, %f16;
	mul.f32 	%f168, %f167, 0fBFB8AA3B;
	ex2.approx.f32 	%f169, %f168;
	add.f32 	%f170, %f165, %f169;
	mul.f32 	%f171, %f159, %f159;
	mul.f32 	%f172, %f171, %f16;
	mul.f32 	%f173, %f172, 0fBFB8AA3B;
	ex2.approx.f32 	%f174, %f173;
	add.f32 	%f175, %f170, %f174;
	mul.f32 	%f176, %f160, %f160;
	mul.f32 	%f177, %f176, %f16;
	mul.f32 	%f178, %f177, 0fBFB8AA3B;
	ex2.approx.f32 	%f179, %f178;
	add.f32 	%f224, %f175, %f179;
	add.s32 	%r44, %r44, 4;
	add.s64 	%rd28, %rd28, 16;
	add.s32 	%r43, %r43, -1;
	setp.ne.s32 	%p6, %r43, 0;
	@%p6 bra 	$L__BB0_7;

$L__BB0_8:
	setp.ge.s32 	%p7, %r44, %r24;
	@%p7 bra 	$L__BB0_15;

	sub.s32 	%r35, %r24, %r44;
	and.b32  	%r46, %r35, 3;
	setp.eq.s32 	%p8, %r46, 0;
	mov.u32 	%r47, %r44;
	@%p8 bra 	$L__BB0_12;

	mul.wide.s32 	%rd21, %r44, 4;
	add.s64 	%rd29, %rd1, %rd21;
	mov.u32 	%r47, %r44;

$L__BB0_11:
	.pragma ""nounroll"";
	ld.global.nc.f32 	%f181, [%rd29];
	sub.f32 	%f182, %f1, %f181;
	mul.f32 	%f183, %f182, %f182;
	mul.f32 	%f184, %f183, %f16;
	mul.f32 	%f185, %f184, 0fBFB8AA3B;
	ex2.approx.f32 	%f186, %f185;
	add.f32 	%f224, %f224, %f186;
	add.s32 	%r47, %r47, 1;
	add.s64 	%rd29, %rd29, 4;
	add.s32 	%r46, %r46, -1;
	setp.ne.s32 	%p9, %r46, 0;
	@%p9 bra 	$L__BB0_11;

$L__BB0_12:
	not.b32 	%r36, %r44;
	add.s32 	%r37, %r36, %r24;
	setp.lt.u32 	%p10, %r37, 3;
	@%p10 bra 	$L__BB0_15;

	mul.wide.s32 	%rd22, %r47, 4;
	add.s64 	%rd23, %rd1, %rd22;
	add.s64 	%rd30, %rd23, 8;

$L__BB0_14:
	ld.global.nc.f32 	%f187, [%rd30+-8];
	sub.f32 	%f188, %f1, %f187;
	mul.f32 	%f189, %f188, %f188;
	mul.f32 	%f190, %f189, %f16;
	mul.f32 	%f191, %f190, 0fBFB8AA3B;
	ex2.approx.f32 	%f192, %f191;
	add.f32 	%f193, %f224, %f192;
	ld.global.nc.f32 	%f194, [%rd30+-4];
	sub.f32 	%f195, %f1, %f194;
	mul.f32 	%f196, %f195, %f195;
	mul.f32 	%f197, %f196, %f16;
	mul.f32 	%f198, %f197, 0fBFB8AA3B;
	ex2.approx.f32 	%f199, %f198;
	add.f32 	%f200, %f193, %f199;
	ld.global.nc.f32 	%f201, [%rd30];
	sub.f32 	%f202, %f1, %f201;
	mul.f32 	%f203, %f202, %f202;
	mul.f32 	%f204, %f203, %f16;
	mul.f32 	%f205, %f204, 0fBFB8AA3B;
	ex2.approx.f32 	%f206, %f205;
	add.f32 	%f207, %f200, %f206;
	ld.global.nc.f32 	%f208, [%rd30+4];
	sub.f32 	%f209, %f1, %f208;
	mul.f32 	%f210, %f209, %f209;
	mul.f32 	%f211, %f210, %f16;
	mul.f32 	%f212, %f211, 0fBFB8AA3B;
	ex2.approx.f32 	%f213, %f212;
	add.f32 	%f224, %f207, %f213;
	add.s64 	%rd30, %rd30, 16;
	add.s32 	%r47, %r47, 4;
	setp.lt.s32 	%p11, %r47, %r24;
	@%p11 bra 	$L__BB0_14;

$L__BB0_15:
	cvta.to.global.u64 	%rd24, %rd15;
	shl.b64 	%rd25, %rd2, 2;
	add.s64 	%rd26, %rd24, %rd25;
	mul.f32 	%f214, %f224, %f17;
	st.global.f32 	[%rd26], %f214;

$L__BB0_16:
	ret;

}
	// .globl	statsviz_kde2d_evaluate_fp32
.visible .entry statsviz_kde2d_evaluate_fp32(
	.param .u64 statsviz_kde2d_evaluate_fp32_param_0,
	.param .u64 statsviz_kde2d_evaluate_fp32_param_1,
	.param .u64 statsviz_kde2d_evaluate_fp32_param_2,
	.param .u64 statsviz_kde2d_evaluate_fp32_param_3,
	.param .u64 statsviz_kde2d_evaluate_fp32_param_4,
	.param .u32 statsviz_kde2d_evaluate_fp32_param_5,
	.param .u32 statsviz_kde2d_evaluate_fp32_param_6,
	.param .u32 statsviz_kde2d_evaluate_fp32_param_7,
	.param .f32 statsviz_kde2d_evaluate_fp32_param_8,
	.param .f32 statsviz_kde2d_evaluate_fp32_param_9,
	.param .f32 statsviz_kde2d_evaluate_fp32_param_10
)
{
	.reg .pred 	%p<7>;
	.reg .f32 	%f<81>;
	.reg .b32 	%r<28>;
	.reg .b64 	%rd<32>;


	ld.param.u64 	%rd16, [statsviz_kde2d_evaluate_fp32_param_0];
	ld.param.u64 	%rd17, [statsviz_kde2d_evaluate_fp32_param_1];
	ld.param.u64 	%rd13, [statsviz_kde2d_evaluate_fp32_param_2];
	ld.param.u64 	%rd14, [statsviz_kde2d_evaluate_fp32_param_3];
	ld.param.u64 	%rd15, [statsviz_kde2d_evaluate_fp32_param_4];
	ld.param.u32 	%r11, [statsviz_kde2d_evaluate_fp32_param_5];
	ld.param.u32 	%r12, [statsviz_kde2d_evaluate_fp32_param_6];
	ld.param.u32 	%r13, [statsviz_kde2d_evaluate_fp32_param_7];
	ld.param.f32 	%f10, [statsviz_kde2d_evaluate_fp32_param_8];
	ld.param.f32 	%f11, [statsviz_kde2d_evaluate_fp32_param_9];
	ld.param.f32 	%f12, [statsviz_kde2d_evaluate_fp32_param_10];
	cvta.to.global.u64 	%rd1, %rd17;
	cvta.to.global.u64 	%rd2, %rd16;
	mov.u32 	%r14, %ntid.x;
	mov.u32 	%r15, %ctaid.x;
	mov.u32 	%r16, %tid.x;
	mad.lo.s32 	%r1, %r15, %r14, %r16;
	mul.lo.s32 	%r17, %r13, %r12;
	setp.ge.s32 	%p1, %r1, %r17;
	@%p1 bra 	$L__BB1_9;

	cvta.to.global.u64 	%rd18, %rd13;
	div.s32 	%r18, %r1, %r12;
	mul.lo.s32 	%r19, %r18, %r12;
	sub.s32 	%r20, %r1, %r19;
	mul.wide.s32 	%rd19, %r20, 4;
	add.s64 	%rd20, %rd18, %rd19;
	ld.global.nc.f32 	%f1, [%rd20];
	cvta.to.global.u64 	%rd21, %rd14;
	mul.wide.s32 	%rd22, %r18, 4;
	add.s64 	%rd23, %rd21, %rd22;
	ld.global.nc.f32 	%f2, [%rd23];
	setp.lt.s32 	%p2, %r11, 1;
	mov.f32 	%f80, 0f00000000;
	@%p2 bra 	$L__BB1_8;

	add.s32 	%r22, %r11, -1;
	and.b32  	%r27, %r11, 3;
	setp.lt.u32 	%p3, %r22, 3;
	mov.f32 	%f80, 0f00000000;
	mov.u32 	%r26, 0;
	@%p3 bra 	$L__BB1_5;

	sub.s32 	%r25, %r11, %r27;
	mov.f32 	%f80, 0f00000000;
	mov.u32 	%r26, 0;
	mov.u64 	%rd28, %rd1;
	mov.u64 	%rd29, %rd2;

$L__BB1_4:
	ld.global.nc.f32 	%f17, [%rd29];
	sub.f32 	%f18, %f1, %f17;
	ld.global.nc.f32 	%f19, [%rd28];
	sub.f32 	%f20, %f2, %f19;
	mul.f32 	%f21, %f18, %f18;
	mul.f32 	%f22, %f20, %f20;
	mul.f32 	%f23, %f22, %f11;
	fma.rn.f32 	%f24, %f21, %f10, %f23;
	mul.f32 	%f25, %f24, 0fBF000000;
	mul.f32 	%f26, %f25, 0f3FB8AA3B;
	ex2.approx.f32 	%f27, %f26;
	add.f32 	%f28, %f80, %f27;
	ld.global.nc.f32 	%f29, [%rd29+4];
	sub.f32 	%f30, %f1, %f29;
	ld.global.nc.f32 	%f31, [%rd28+4];
	sub.f32 	%f32, %f2, %f31;
	mul.f32 	%f33, %f30, %f30;
	mul.f32 	%f34, %f32, %f32;
	mul.f32 	%f35, %f34, %f11;
	fma.rn.f32 	%f36, %f33, %f10, %f35;
	mul.f32 	%f37, %f36, 0fBF000000;
	mul.f32 	%f38, %f37, 0f3FB8AA3B;
	ex2.approx.f32 	%f39, %f38;
	add.f32 	%f40, %f28, %f39;
	ld.global.nc.f32 	%f41, [%rd29+8];
	sub.f32 	%f42, %f1, %f41;
	ld.global.nc.f32 	%f43, [%rd28+8];
	sub.f32 	%f44, %f2, %f43;
	mul.f32 	%f45, %f42, %f42;
	mul.f32 	%f46, %f44, %f44;
	mul.f32 	%f47, %f46, %f11;
	fma.rn.f32 	%f48, %f45, %f10, %f47;
	mul.f32 	%f49, %f48, 0fBF000000;
	mul.f32 	%f50, %f49, 0f3FB8AA3B;
	ex2.approx.f32 	%f51, %f50;
	add.f32 	%f52, %f40, %f51;
	ld.global.nc.f32 	%f53, [%rd29+12];
	sub.f32 	%f54, %f1, %f53;
	ld.global.nc.f32 	%f55, [%rd28+12];
	sub.f32 	%f56, %f2, %f55;
	mul.f32 	%f57, %f54, %f54;
	mul.f32 	%f58, %f56, %f56;
	mul.f32 	%f59, %f58, %f11;
	fma.rn.f32 	%f60, %f57, %f10, %f59;
	mul.f32 	%f61, %f60, 0fBF000000;
	mul.f32 	%f62, %f61, 0f3FB8AA3B;
	ex2.approx.f32 	%f63, %f62;
	add.f32 	%f80, %f52, %f63;
	add.s32 	%r26, %r26, 4;
	add.s64 	%rd29, %rd29, 16;
	add.s64 	%rd28, %rd28, 16;
	add.s32 	%r25, %r25, -4;
	setp.ne.s32 	%p4, %r25, 0;
	@%p4 bra 	$L__BB1_4;

$L__BB1_5:
	setp.eq.s32 	%p5, %r27, 0;
	@%p5 bra 	$L__BB1_8;

	mul.wide.s32 	%rd24, %r26, 4;
	add.s64 	%rd31, %rd1, %rd24;
	add.s64 	%rd30, %rd2, %rd24;

$L__BB1_7:
	.pragma ""nounroll"";
	ld.global.nc.f32 	%f64, [%rd30];
	sub.f32 	%f65, %f1, %f64;
	ld.global.nc.f32 	%f66, [%rd31];
	sub.f32 	%f67, %f2, %f66;
	mul.f32 	%f68, %f65, %f65;
	mul.f32 	%f69, %f67, %f67;
	mul.f32 	%f70, %f69, %f11;
	fma.rn.f32 	%f71, %f68, %f10, %f70;
	mul.f32 	%f72, %f71, 0fBF000000;
	mul.f32 	%f73, %f72, 0f3FB8AA3B;
	ex2.approx.f32 	%f74, %f73;
	add.f32 	%f80, %f80, %f74;
	add.s64 	%rd31, %rd31, 4;
	add.s64 	%rd30, %rd30, 4;
	add.s32 	%r27, %r27, -1;
	setp.ne.s32 	%p6, %r27, 0;
	@%p6 bra 	$L__BB1_7;

$L__BB1_8:
	cvta.to.global.u64 	%rd25, %rd15;
	mul.wide.s32 	%rd26, %r1, 4;
	add.s64 	%rd27, %rd25, %rd26;
	mul.f32 	%f75, %f80, %f12;
	st.global.f32 	[%rd27], %f75;

$L__BB1_9:
	ret;

}

";
}